version: 2

sources:
  - name: raw_taxi_data
    description: Processed NYC taxi data from S3
    meta:
      external_location: "s3://nyc-taxi-data-lake-ygzcn2t2/processed-data/**/*.parquet"
    
    tables:
      - name: trips
        description: Processed taxi trip records
        external:
          location: "s3://nyc-taxi-data-lake-ygzcn2t2/processed-data/**/*.parquet"
          file_format: parquet